---
title: "BMI 651"
author: "Joshua Burkhart"
date: "February 22, 2016"
output: 
  pdf_document: 
    fig_width: 9
    fig_height: 6
    latex_engine: xelatex
---
# HW4: APPENDIX

```{r global_options, echo=FALSE, include=FALSE, error=FALSE}
knitr::opts_chunk$set(fig.path = "Figs/",
                      message = FALSE,
                      warning = FALSE,
                      include = TRUE,
                      echo = TRUE,
                      error = TRUE,
                      fig.width = 11,
                      comment = NA)
```

```{r, echo=FALSE, include=FALSE}
library(MASS)
library(plyr) #this must be loaded before dplyr 
library(dplyr)
library(ggplot2)
library(broom)
library(knitr)
library(magrittr)
library(tree)
library(rpart)
library(adabag)
set.seed(1234)
```

```{r}
spam.df <- read.table("~/SoftwareProjects/StatisticalMethodsInCompBio/HW4/spam.data")
```

##1

```{r}
spam.df %>% dim()
spam.df[,58] %>% table()
spam.df[,58] %>% table() %>% as.vector() %>% .[1]/spam.df %>% nrow()
spam.df[,58] %>% table() %>% as.vector() %>% .[2]/spam.df %>% nrow()
```

##2

###2A

```{r}
index <- sample(1:nrow(spam.df),round(0.5*nrow(spam.df)))
spam.df_train <- spam.df[index,]
spam.df_test <- spam.df[-index,]
```

###2B

```{r}
duplicated(spam.df) %>% table()

spam.df_unique <- unique(spam.df)

spam.df_unique %>% dim()
spam.df_unique[,58] %>% table()
spam.df_unique[,58] %>% table() %>% as.vector() %>% .[1]/spam.df_unique %>% nrow()
spam.df_unique[,58] %>% table() %>% as.vector() %>% .[2]/spam.df_unique %>% nrow()

index <- sample(1:nrow(spam.df_unique),round(0.5*nrow(spam.df_unique)))
spam.df_train <- spam.df_unique[index,]
spam.df_test <- spam.df_unique[-index,]

intersect(spam.df_train,spam.df_test) %>% nrow()
```

###2C

```{r}
spam.df_train %>% dim()
spam.df_test %>% dim()
```

###2D

```{r}
# training set
spam.df_train[,58] %>% table()
spam.df_train[,58] %>% table() %>% as.vector() %>% .[1]/spam.df_train %>% nrow()
spam.df_train[,58] %>% table() %>% as.vector() %>% .[2]/spam.df_train %>% nrow()

# test set
spam.df_test[,58] %>% table()
spam.df_test[,58] %>% table() %>% as.vector() %>% .[1]/spam.df_test %>% nrow()
spam.df_test[,58] %>% table() %>% as.vector() %>% .[2]/spam.df_test %>% nrow()
```

##3

###3A

```{r}
# applying factor() to the response forces production of a classification tree
# (Brian, A., & Ripley, M. B. (2016). Package “ tree .”)
spam.tree <- tree(factor(spam.df_train$V58)~.,data=spam.df_train)

# perform K=10 fold cross validation
spam.tree_cv <- cv.tree(spam.tree,K=10)

# prune the tree, allowing 12 terminal nodes
spam.tree_pruned <- prune.tree(spam.tree,best=12)
```

###3B

```{r}
plot(spam.tree_cv,main="Tree Size vs Deviance (Number of Misclassifications)\n\n")
```

###3C

```{r}
plot(spam.tree_pruned,main="'Pruned' Tree\n")
text(spam.tree_pruned)
```

###3D

```{r}
# perform prediction on test dataset
spam.test_pred <- predict(spam.tree_pruned,spam.df_test[,-58],type="class")

# calculate misclassification percentage
table(as.integer(as.character(spam.test_pred)) == spam.df_test[,58]) %>% .[1] / length(spam.test_pred)
```

###3E

```{r}
spam.tree_pruned %>% summary()
```

##4

###4A

```{r}
spam.df_train$V58 <- factor(spam.df_train$V58)
spam.bagging <- bagging(V58~.,data=spam.df_train,mfinal=100)
```

###4B

```{r}
imp <- data.frame(spam.bagging$importance)
ggplot(data=imp, aes(x=rownames(imp),y=imp$spam.bagging.importance)) +
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab("Variable") +
  ylab("Importance") +
  ggtitle("Bagging Variable Importance")
```

###4C

```{r}
spam.df_test$V58 <- factor(spam.df_test$V58)
spam.bagging_test_pred <- predict(spam.bagging,spam.df_test,type="class")
spam.bagging_test_pred$error
```

##5

###5A

```{r}
spam.boosting <- boosting(V58~.,data=spam.df_train,mfinal=100)
```

###5B

```{r}
imp <- data.frame(spam.boosting$importance)
ggplot(data=imp, aes(x=rownames(imp),y=imp$spam.boosting.importance)) +
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab("Variable") +
  ylab("Importance") +
  ggtitle("Boosting Variable Importance")
```

###5C

```{r}
spam.boosting_test_pred <- predict(spam.boosting,spam.df_test,type="class")
spam.boosting_test_pred$error
```
